// AUTO-GENERATED by scripts/build-jetbrains.mjs — DO NOT EDIT BY HAND.
// Source of truth: scripts/manifest.mjs
package com.makinda.icons

import com.intellij.ide.FileIconProvider
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.IconLoader
import com.intellij.openapi.vfs.VirtualFile
import javax.swing.Icon

class MakindaFileIconProvider : FileIconProvider {
    override fun getIcon(file: VirtualFile, flags: Int, project: Project?): Icon? {
        if (file.isDirectory) return null
        val name = file.name.lowercase()
        BY_NAME[name]?.let { return it }
        val ext = file.extension?.lowercase() ?: return null
        return BY_EXT[ext]
    }

    companion object {
        private fun load(name: String): Icon =
            IconLoader.getIcon("/icons/makinda/$name.svg", MakindaFileIconProvider::class.java)

        private val ICON_ARCHIVE: Icon = load("archive")
        private val ICON_ASTRO: Icon = load("astro")
        private val ICON_AUDIO: Icon = load("audio")
        private val ICON_AUTHORS: Icon = load("authors")
        private val ICON_BASH: Icon = load("bash")
        private val ICON_BATCH: Icon = load("batch")
        private val ICON_BINARY: Icon = load("binary")
        private val ICON_C: Icon = load("c")
        private val ICON_CHANGELOG: Icon = load("changelog")
        private val ICON_CODE: Icon = load("code")
        private val ICON_CODE_OF_CONDUCT: Icon = load("code-of-conduct")
        private val ICON_CODE_SQUARE: Icon = load("code-square")
        private val ICON_COMMAND_LINE: Icon = load("command-line")
        private val ICON_CONFIG: Icon = load("config")
        private val ICON_CONTRIBUTING: Icon = load("contributing")
        private val ICON_CPP: Icon = load("cpp")
        private val ICON_CSS: Icon = load("css")
        private val ICON_CSV: Icon = load("csv")
        private val ICON_DART: Icon = load("dart")
        private val ICON_DATABASE: Icon = load("database")
        private val ICON_DOC: Icon = load("doc")
        private val ICON_DOTENV: Icon = load("dotenv")
        private val ICON_EDITORCONFIG: Icon = load("editorconfig")
        private val ICON_ENV: Icon = load("env")
        private val ICON_FIGMA: Icon = load("figma")
        private val ICON_FILE: Icon = load("file")
        private val ICON_FISH: Icon = load("fish")
        private val ICON_FONT: Icon = load("font")
        private val ICON_GIF: Icon = load("gif")
        private val ICON_GITATTRIBUTES: Icon = load("gitattributes")
        private val ICON_GITHUB: Icon = load("github")
        private val ICON_GITIGNORE: Icon = load("gitignore")
        private val ICON_GITMODULES: Icon = load("gitmodules")
        private val ICON_GO: Icon = load("go")
        private val ICON_HTML: Icon = load("html")
        private val ICON_IMAGE: Icon = load("image")
        private val ICON_JAVA: Icon = load("java")
        private val ICON_JAVASCRIPT: Icon = load("javascript")
        private val ICON_JS: Icon = load("js")
        private val ICON_JSON: Icon = load("json")
        private val ICON_LICENSE: Icon = load("license")
        private val ICON_LOCK: Icon = load("lock")
        private val ICON_MARKDOWN: Icon = load("markdown")
        private val ICON_NEXT: Icon = load("next")
        private val ICON_NOTICE: Icon = load("notice")
        private val ICON_NPMIGNORE: Icon = load("npmignore")
        private val ICON_NUSHELL: Icon = load("nushell")
        private val ICON_PDF: Icon = load("pdf")
        private val ICON_PHP: Icon = load("php")
        private val ICON_POWERSHELL: Icon = load("powershell")
        private val ICON_PPT: Icon = load("ppt")
        private val ICON_PYTHON: Icon = load("python")
        private val ICON_README: Icon = load("readme")
        private val ICON_RUBY: Icon = load("ruby")
        private val ICON_RUST: Icon = load("rust")
        private val ICON_SECURITY: Icon = load("security")
        private val ICON_SQL: Icon = load("sql")
        private val ICON_SVELTE: Icon = load("svelte")
        private val ICON_SVG: Icon = load("svg")
        private val ICON_TODO: Icon = load("todo")
        private val ICON_TOML: Icon = load("toml")
        private val ICON_TS: Icon = load("ts")
        private val ICON_TSV: Icon = load("tsv")
        private val ICON_TXT: Icon = load("txt")
        private val ICON_TYPESCRIPT: Icon = load("typescript")
        private val ICON_VIDEO: Icon = load("video")
        private val ICON_VUE: Icon = load("vue")
        private val ICON_XML: Icon = load("xml")
        private val ICON_YAML: Icon = load("yaml")
        private val ICON_ZSH: Icon = load("zsh")

        private val ICON_AIFF: Icon = load("aiff")
        private val ICON_CERTIFICATE: Icon = load("certificate")
        private val ICON_CONTRACT: Icon = load("contract")
        private val ICON_EPS: Icon = load("eps")
        private val ICON_EXCEL: Icon = load("excel")
        private val ICON_JPG_ICON: Icon = load("jpg-icon")
        private val ICON_MIDI: Icon = load("midi")
        private val ICON_MOV_ICON: Icon = load("mov-icon")
        private val ICON_MP3_ICON: Icon = load("mp3-icon")
        private val ICON_MP4_ICON: Icon = load("mp4-icon")
        private val ICON_MUSIC_FILE: Icon = load("music-file")
        private val ICON_ODF: Icon = load("odf")
        private val ICON_PNG_ICON: Icon = load("png-icon")
        private val ICON_POWERPOINT: Icon = load("powerpoint")
        private val ICON_SHIELD: Icon = load("shield")
        private val ICON_SVG_ICON: Icon = load("svg-icon")
        private val ICON_TEX: Icon = load("tex")
        private val ICON_USER_FILE: Icon = load("user-file")
        private val ICON_VECTOR: Icon = load("vector")
        private val ICON_WAV_ICON: Icon = load("wav-icon")
        private val ICON_WAVEFORM: Icon = load("waveform")
        private val ICON_WORD: Icon = load("word")
        private val ICON_XML_ICON: Icon = load("xml-icon")
        private val ICON_ZIP_ICON: Icon = load("zip-icon")

        private val BY_EXT: Map<String, Icon> = mapOf(
        "7z" to ICON_ARCHIVE,
        "aac" to ICON_AUDIO,
        "adoc" to ICON_MARKDOWN,
        "astro" to ICON_ASTRO,
        "avi" to ICON_VIDEO,
        "avif" to ICON_IMAGE,
        "bash" to ICON_BASH,
        "bat" to ICON_BATCH,
        "bin" to ICON_BINARY,
        "bmp" to ICON_IMAGE,
        "bz2" to ICON_ARCHIVE,
        "c" to ICON_C,
        "cc" to ICON_CPP,
        "cfg" to ICON_CONFIG,
        "cjs" to ICON_JS,
        "class" to ICON_JAVA,
        "cmd" to ICON_BATCH,
        "coffee" to ICON_CODE,
        "conf" to ICON_CONFIG,
        "config" to ICON_CONFIG,
        "cpp" to ICON_CPP,
        "css" to ICON_CSS,
        "csv" to ICON_CSV,
        "cts" to ICON_TS,
        "cxx" to ICON_CPP,
        "dart" to ICON_DART,
        "db" to ICON_DATABASE,
        "dll" to ICON_BINARY,
        "doc" to ICON_DOC,
        "docx" to ICON_DOC,
        "env" to ICON_ENV,
        "eot" to ICON_FONT,
        "erb" to ICON_RUBY,
        "exe" to ICON_BINARY,
        "fig" to ICON_FIGMA,
        "fish" to ICON_FISH,
        "flac" to ICON_AUDIO,
        "flv" to ICON_VIDEO,
        "gemspec" to ICON_RUBY,
        "gif" to ICON_GIF,
        "go" to ICON_GO,
        "gz" to ICON_ARCHIVE,
        "h" to ICON_C,
        "heic" to ICON_IMAGE,
        "hh" to ICON_CPP,
        "hpp" to ICON_CPP,
        "htm" to ICON_HTML,
        "html" to ICON_HTML,
        "hxx" to ICON_CPP,
        "ico" to ICON_IMAGE,
        "ini" to ICON_CONFIG,
        "ipynb" to ICON_PYTHON,
        "jar" to ICON_JAVA,
        "java" to ICON_JAVA,
        "jpeg" to ICON_IMAGE,
        "jpg" to ICON_IMAGE,
        "js" to ICON_JS,
        "json" to ICON_JSON,
        "json5" to ICON_JSON,
        "jsonc" to ICON_JSON,
        "jsx" to ICON_JS,
        "key" to ICON_PPT,
        "less" to ICON_CSS,
        "log" to ICON_TXT,
        "m4a" to ICON_AUDIO,
        "markdown" to ICON_MARKDOWN,
        "md" to ICON_MARKDOWN,
        "mdown" to ICON_MARKDOWN,
        "mdx" to ICON_MARKDOWN,
        "mjs" to ICON_JS,
        "mkv" to ICON_VIDEO,
        "mov" to ICON_VIDEO,
        "mp3" to ICON_AUDIO,
        "mp4" to ICON_VIDEO,
        "mts" to ICON_TS,
        "nu" to ICON_NUSHELL,
        "o" to ICON_BINARY,
        "odt" to ICON_DOC,
        "ogg" to ICON_AUDIO,
        "otf" to ICON_FONT,
        "pcss" to ICON_CSS,
        "pdf" to ICON_PDF,
        "php" to ICON_PHP,
        "phtml" to ICON_PHP,
        "plist" to ICON_XML,
        "png" to ICON_IMAGE,
        "ppt" to ICON_PPT,
        "pptx" to ICON_PPT,
        "properties" to ICON_CONFIG,
        "ps1" to ICON_POWERSHELL,
        "psd1" to ICON_POWERSHELL,
        "psm1" to ICON_POWERSHELL,
        "psx" to ICON_POWERSHELL,
        "py" to ICON_PYTHON,
        "pyc" to ICON_PYTHON,
        "pyi" to ICON_PYTHON,
        "pyw" to ICON_PYTHON,
        "rar" to ICON_ARCHIVE,
        "rb" to ICON_RUBY,
        "rs" to ICON_RUST,
        "rst" to ICON_MARKDOWN,
        "rtf" to ICON_DOC,
        "sass" to ICON_CSS,
        "scss" to ICON_CSS,
        "sh" to ICON_BASH,
        "so" to ICON_BINARY,
        "sql" to ICON_SQL,
        "sqlite" to ICON_DATABASE,
        "sqlite3" to ICON_DATABASE,
        "styl" to ICON_CSS,
        "svelte" to ICON_SVELTE,
        "svg" to ICON_SVG,
        "tar" to ICON_ARCHIVE,
        "tgz" to ICON_ARCHIVE,
        "tiff" to ICON_IMAGE,
        "toml" to ICON_TOML,
        "ts" to ICON_TS,
        "tsv" to ICON_TSV,
        "tsx" to ICON_TS,
        "ttf" to ICON_FONT,
        "txt" to ICON_TXT,
        "vue" to ICON_VUE,
        "wasm" to ICON_BINARY,
        "wav" to ICON_AUDIO,
        "webm" to ICON_VIDEO,
        "webp" to ICON_IMAGE,
        "woff" to ICON_FONT,
        "woff2" to ICON_FONT,
        "xhtml" to ICON_HTML,
        "xml" to ICON_XML,
        "xsd" to ICON_XML,
        "xsl" to ICON_XML,
        "xslt" to ICON_XML,
        "xz" to ICON_ARCHIVE,
        "yaml" to ICON_YAML,
        "yml" to ICON_YAML,
        "zip" to ICON_ARCHIVE,
        "zsh" to ICON_ZSH,
        "abc" to ICON_MUSIC_FILE,
        "ai" to ICON_EPS,
        "aif" to ICON_AIFF,
        "aifc" to ICON_AIFF,
        "aiff" to ICON_AIFF,
        "bib" to ICON_TEX,
        "cab" to ICON_ZIP_ICON,
        "cdr" to ICON_VECTOR,
        "cer" to ICON_SHIELD,
        "cls" to ICON_TEX,
        "csr" to ICON_SHIELD,
        "crt" to ICON_SHIELD,
        "der" to ICON_SHIELD,
        "docm" to ICON_WORD,
        "dot" to ICON_WORD,
        "dotx" to ICON_WORD,
        "eps" to ICON_EPS,
        "jfif" to ICON_JPG_ICON,
        "jpe" to ICON_JPG_ICON,
        "kar" to ICON_MIDI,
        "lic" to ICON_CERTIFICATE,
        "license" to ICON_CERTIFICATE,
        "ltx" to ICON_TEX,
        "lz" to ICON_ZIP_ICON,
        "lzma" to ICON_ZIP_ICON,
        "lzo" to ICON_ZIP_ICON,
        "m4v" to ICON_MP4_ICON,
        "mid" to ICON_MIDI,
        "midi" to ICON_MIDI,
        "mov" to ICON_MOV_ICON,
        "mp3" to ICON_MP3_ICON,
        "mp4" to ICON_MP4_ICON,
        "musicxml" to ICON_MUSIC_FILE,
        "mxl" to ICON_MUSIC_FILE,
        "numbers" to ICON_EXCEL,
        "odb" to ICON_ODF,
        "odf" to ICON_ODF,
        "odg" to ICON_ODF,
        "odm" to ICON_ODF,
        "odp" to ICON_POWERPOINT,
        "ods" to ICON_EXCEL,
        "oga" to ICON_WAVEFORM,
        "opus" to ICON_WAVEFORM,
        "p12" to ICON_SHIELD,
        "p7b" to ICON_SHIELD,
        "pem" to ICON_SHIELD,
        "pfx" to ICON_SHIELD,
        "png" to ICON_PNG_ICON,
        "pot" to ICON_POWERPOINT,
        "potx" to ICON_POWERPOINT,
        "pps" to ICON_POWERPOINT,
        "ppsx" to ICON_POWERPOINT,
        "sk" to ICON_VECTOR,
        "sk1" to ICON_VECTOR,
        "spx" to ICON_WAVEFORM,
        "sty" to ICON_TEX,
        "svg" to ICON_SVG_ICON,
        "tex" to ICON_TEX,
        "vcf" to ICON_USER_FILE,
        "vcard" to ICON_USER_FILE,
        "wav" to ICON_WAV_ICON,
        "wsdl" to ICON_XML_ICON,
        "xaml" to ICON_XML_ICON,
        "xls" to ICON_EXCEL,
        "xlsm" to ICON_EXCEL,
        "xlsx" to ICON_EXCEL,
        "xlsm" to ICON_EXCEL,
        )

        private val BY_NAME: Map<String, Icon> = mapOf(
        ".bash_history" to ICON_BASH,
        ".bash_logout" to ICON_BASH,
        ".bash_profile" to ICON_BASH,
        ".bashrc" to ICON_BASH,
        ".browserslistrc" to ICON_CONFIG,
        ".dockerignore" to ICON_COMMAND_LINE,
        ".editorconfig" to ICON_EDITORCONFIG,
        ".env" to ICON_DOTENV,
        ".env.development" to ICON_DOTENV,
        ".env.example" to ICON_DOTENV,
        ".env.local" to ICON_DOTENV,
        ".env.production" to ICON_DOTENV,
        ".env.sample" to ICON_DOTENV,
        ".env.staging" to ICON_DOTENV,
        ".env.test" to ICON_DOTENV,
        ".eslintignore" to ICON_CONFIG,
        ".eslintrc" to ICON_CONFIG,
        ".eslintrc.json" to ICON_CONFIG,
        ".gitattributes" to ICON_GITATTRIBUTES,
        ".gitignore" to ICON_GITIGNORE,
        ".gitignore_global" to ICON_GITIGNORE,
        ".gitmodules" to ICON_GITMODULES,
        ".npmignore" to ICON_NPMIGNORE,
        ".npmrc" to ICON_CONFIG,
        ".prettierignore" to ICON_CONFIG,
        ".prettierrc" to ICON_CONFIG,
        ".stylelintrc" to ICON_CONFIG,
        ".zlogin" to ICON_ZSH,
        ".zlogout" to ICON_ZSH,
        ".zprofile" to ICON_ZSH,
        ".zsh_history" to ICON_ZSH,
        ".zsh_profile" to ICON_ZSH,
        ".zshenv" to ICON_ZSH,
        ".zshrc" to ICON_ZSH,
        "authors" to ICON_AUTHORS,
        "authors.md" to ICON_AUTHORS,
        "authors.txt" to ICON_AUTHORS,
        "bun.lockb" to ICON_LOCK,
        "cargo.lock" to ICON_RUST,
        "cargo.toml" to ICON_RUST,
        "changelog" to ICON_CHANGELOG,
        "changelog.md" to ICON_CHANGELOG,
        "changelog.txt" to ICON_CHANGELOG,
        "changes" to ICON_CHANGELOG,
        "changes.md" to ICON_CHANGELOG,
        "code-of-conduct.md" to ICON_CODE_OF_CONDUCT,
        "code_of_conduct.md" to ICON_CODE_OF_CONDUCT,
        "codeowners" to ICON_GITHUB,
        "composer.lock" to ICON_LOCK,
        "config.fish" to ICON_FISH,
        "contributing" to ICON_CONTRIBUTING,
        "contributing.md" to ICON_CONTRIBUTING,
        "contributing.txt" to ICON_CONTRIBUTING,
        "copying" to ICON_LICENSE,
        "docker-compose.yaml" to ICON_YAML,
        "docker-compose.yml" to ICON_YAML,
        "dockerfile" to ICON_COMMAND_LINE,
        "funding.yml" to ICON_GITHUB,
        "gemfile" to ICON_RUBY,
        "gemfile.lock" to ICON_RUBY,
        "go.mod" to ICON_GO,
        "go.sum" to ICON_GO,
        "history.md" to ICON_CHANGELOG,
        "history.txt" to ICON_CHANGELOG,
        "issue_template.md" to ICON_GITHUB,
        "jsconfig.json" to ICON_JSON,
        "license" to ICON_LICENSE,
        "license.md" to ICON_LICENSE,
        "license.txt" to ICON_LICENSE,
        "maintainers" to ICON_AUTHORS,
        "maintainers.md" to ICON_AUTHORS,
        "makefile" to ICON_COMMAND_LINE,
        "next.config.cjs" to ICON_NEXT,
        "next.config.js" to ICON_NEXT,
        "next.config.mjs" to ICON_NEXT,
        "next.config.ts" to ICON_NEXT,
        "notice" to ICON_NOTICE,
        "notice.md" to ICON_NOTICE,
        "notice.txt" to ICON_NOTICE,
        "package-lock.json" to ICON_JSON,
        "package.json" to ICON_JSON,
        "pipfile" to ICON_PYTHON,
        "pipfile.lock" to ICON_PYTHON,
        "pnpm-lock.yaml" to ICON_LOCK,
        "poetry.lock" to ICON_LOCK,
        "pull_request_template.md" to ICON_GITHUB,
        "pyproject.toml" to ICON_PYTHON,
        "rakefile" to ICON_RUBY,
        "readme" to ICON_README,
        "readme.adoc" to ICON_README,
        "readme.markdown" to ICON_README,
        "readme.md" to ICON_README,
        "readme.rst" to ICON_README,
        "readme.txt" to ICON_README,
        "releasenotes.md" to ICON_CHANGELOG,
        "requirements.txt" to ICON_PYTHON,
        "security" to ICON_SECURITY,
        "security.md" to ICON_SECURITY,
        "setup.cfg" to ICON_PYTHON,
        "setup.py" to ICON_PYTHON,
        "tasks.md" to ICON_TODO,
        "todo" to ICON_TODO,
        "todo.md" to ICON_TODO,
        "todo.txt" to ICON_TODO,
        "tsconfig.base.json" to ICON_JSON,
        "tsconfig.json" to ICON_JSON,
        "yarn.lock" to ICON_LOCK,
        "agreement.md" to ICON_CONTRACT,
        "copying" to ICON_CERTIFICATE,
        "license" to ICON_CERTIFICATE,
        "license.md" to ICON_CERTIFICATE,
        "notice" to ICON_CERTIFICATE,
        "terms" to ICON_CONTRACT,
        "terms.md" to ICON_CONTRACT,
        "terms.txt" to ICON_CONTRACT,
        )
    }
}
