// AUTO-GENERATED by scripts/build-jetbrains.mjs — DO NOT EDIT BY HAND.
// Source of truth: scripts/manifest.mjs
package com.makinda.icons

import com.intellij.ide.FileIconProvider
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.IconLoader
import com.intellij.openapi.vfs.VirtualFile
import javax.swing.Icon

class MakindaFileIconProvider : FileIconProvider {
    override fun getIcon(file: VirtualFile, flags: Int, project: Project?): Icon? {
        if (file.isDirectory) return null
        val name = file.name.lowercase()
        BY_NAME[name]?.let { return it }
        val ext = file.extension?.lowercase() ?: return null
        return BY_EXT[ext]
    }

    companion object {
        private fun load(name: String): Icon =
            IconLoader.getIcon("/icons/makinda/$name.svg", MakindaFileIconProvider::class.java)

        private val ICON_ARCHIVE: Icon = load("archive")
        private val ICON_AUDIO: Icon = load("audio")
        private val ICON_CODE: Icon = load("code")
        private val ICON_CODE_SQUARE: Icon = load("code-square")
        private val ICON_COMMAND_LINE: Icon = load("command-line")
        private val ICON_CONFIG: Icon = load("config")
        private val ICON_CSS: Icon = load("css")
        private val ICON_CSV: Icon = load("csv")
        private val ICON_DATABASE: Icon = load("database")
        private val ICON_DOC: Icon = load("doc")
        private val ICON_FIGMA: Icon = load("figma")
        private val ICON_FILE: Icon = load("file")
        private val ICON_FOLDER: Icon = load("folder")
        private val ICON_FOLDER_AUDIO: Icon = load("folder-audio")
        private val ICON_FOLDER_CLOUD: Icon = load("folder-cloud")
        private val ICON_FOLDER_CODE: Icon = load("folder-code")
        private val ICON_FOLDER_FAVOURITE: Icon = load("folder-favourite")
        private val ICON_FOLDER_LIBRARY: Icon = load("folder-library")
        private val ICON_FOLDER_LOCKED: Icon = load("folder-locked")
        private val ICON_FOLDER_MANAGEMENT: Icon = load("folder-management")
        private val ICON_FOLDER_MUSIC: Icon = load("folder-music")
        private val ICON_FOLDER_OPEN: Icon = load("folder-open")
        private val ICON_FOLDER_SEARCH: Icon = load("folder-search")
        private val ICON_FOLDER_SHARED: Icon = load("folder-shared")
        private val ICON_FOLDER_VIDEO: Icon = load("folder-video")
        private val ICON_FOLDER_ZIP: Icon = load("folder-zip")
        private val ICON_GIF: Icon = load("gif")
        private val ICON_GITHUB: Icon = load("github")
        private val ICON_HTML: Icon = load("html")
        private val ICON_IMAGE: Icon = load("image")
        private val ICON_JSON: Icon = load("json")
        private val ICON_LICENSE: Icon = load("license")
        private val ICON_MARKDOWN: Icon = load("markdown")
        private val ICON_PDF: Icon = load("pdf")
        private val ICON_PPT: Icon = load("ppt")
        private val ICON_SVG: Icon = load("svg")
        private val ICON_TXT: Icon = load("txt")
        private val ICON_VIDEO: Icon = load("video")
        private val ICON_XML: Icon = load("xml")
        private val ICON_YAML: Icon = load("yaml")

        private val BY_EXT: Map<String, Icon> = mapOf(
        "7z" to ICON_ARCHIVE,
        "aac" to ICON_AUDIO,
        "adoc" to ICON_MARKDOWN,
        "avi" to ICON_VIDEO,
        "avif" to ICON_IMAGE,
        "bash" to ICON_COMMAND_LINE,
        "bat" to ICON_COMMAND_LINE,
        "bmp" to ICON_IMAGE,
        "bz2" to ICON_ARCHIVE,
        "cfg" to ICON_CONFIG,
        "cjs" to ICON_CODE,
        "cmd" to ICON_COMMAND_LINE,
        "coffee" to ICON_CODE,
        "conf" to ICON_CONFIG,
        "config" to ICON_CONFIG,
        "css" to ICON_CSS,
        "csv" to ICON_CSV,
        "db" to ICON_DATABASE,
        "doc" to ICON_DOC,
        "docx" to ICON_DOC,
        "env" to ICON_CONFIG,
        "fig" to ICON_FIGMA,
        "fish" to ICON_COMMAND_LINE,
        "flac" to ICON_AUDIO,
        "flv" to ICON_VIDEO,
        "gif" to ICON_GIF,
        "gz" to ICON_ARCHIVE,
        "heic" to ICON_IMAGE,
        "htm" to ICON_HTML,
        "html" to ICON_HTML,
        "ico" to ICON_IMAGE,
        "ini" to ICON_CONFIG,
        "jpeg" to ICON_IMAGE,
        "jpg" to ICON_IMAGE,
        "js" to ICON_CODE,
        "json" to ICON_JSON,
        "json5" to ICON_JSON,
        "jsonc" to ICON_JSON,
        "jsx" to ICON_CODE,
        "key" to ICON_PPT,
        "less" to ICON_CSS,
        "log" to ICON_TXT,
        "m4a" to ICON_AUDIO,
        "markdown" to ICON_MARKDOWN,
        "md" to ICON_MARKDOWN,
        "mdown" to ICON_MARKDOWN,
        "mdx" to ICON_MARKDOWN,
        "mjs" to ICON_CODE,
        "mkv" to ICON_VIDEO,
        "mov" to ICON_VIDEO,
        "mp3" to ICON_AUDIO,
        "mp4" to ICON_VIDEO,
        "odt" to ICON_DOC,
        "ogg" to ICON_AUDIO,
        "pcss" to ICON_CSS,
        "pdf" to ICON_PDF,
        "plist" to ICON_XML,
        "png" to ICON_IMAGE,
        "ppt" to ICON_PPT,
        "pptx" to ICON_PPT,
        "properties" to ICON_CONFIG,
        "ps1" to ICON_COMMAND_LINE,
        "rar" to ICON_ARCHIVE,
        "rst" to ICON_MARKDOWN,
        "rtf" to ICON_DOC,
        "sass" to ICON_CSS,
        "scss" to ICON_CSS,
        "sh" to ICON_COMMAND_LINE,
        "sql" to ICON_DATABASE,
        "sqlite" to ICON_DATABASE,
        "sqlite3" to ICON_DATABASE,
        "styl" to ICON_CSS,
        "svg" to ICON_SVG,
        "tar" to ICON_ARCHIVE,
        "tgz" to ICON_ARCHIVE,
        "tiff" to ICON_IMAGE,
        "toml" to ICON_YAML,
        "ts" to ICON_CODE,
        "tsv" to ICON_CSV,
        "tsx" to ICON_CODE,
        "txt" to ICON_TXT,
        "wav" to ICON_AUDIO,
        "webm" to ICON_VIDEO,
        "webp" to ICON_IMAGE,
        "xhtml" to ICON_HTML,
        "xml" to ICON_XML,
        "xsd" to ICON_XML,
        "xsl" to ICON_XML,
        "xslt" to ICON_XML,
        "xz" to ICON_ARCHIVE,
        "yaml" to ICON_YAML,
        "yml" to ICON_YAML,
        "zip" to ICON_ARCHIVE,
        "zsh" to ICON_COMMAND_LINE,
        )

        private val BY_NAME: Map<String, Icon> = mapOf(
        ".browserslistrc" to ICON_CONFIG,
        ".editorconfig" to ICON_CONFIG,
        ".env" to ICON_CONFIG,
        ".env.development" to ICON_CONFIG,
        ".env.local" to ICON_CONFIG,
        ".env.production" to ICON_CONFIG,
        ".eslintignore" to ICON_CONFIG,
        ".eslintrc" to ICON_CONFIG,
        ".eslintrc.json" to ICON_CONFIG,
        ".gitattributes" to ICON_CONFIG,
        ".gitignore" to ICON_CONFIG,
        ".npmignore" to ICON_CONFIG,
        ".npmrc" to ICON_CONFIG,
        ".prettierignore" to ICON_CONFIG,
        ".prettierrc" to ICON_CONFIG,
        ".stylelintrc" to ICON_CONFIG,
        "codeowners" to ICON_GITHUB,
        "copying" to ICON_LICENSE,
        "funding.yml" to ICON_GITHUB,
        "issue_template.md" to ICON_GITHUB,
        "jsconfig.json" to ICON_JSON,
        "license" to ICON_LICENSE,
        "license.md" to ICON_LICENSE,
        "license.txt" to ICON_LICENSE,
        "notice" to ICON_LICENSE,
        "package.json" to ICON_JSON,
        "pull_request_template.md" to ICON_GITHUB,
        "readme" to ICON_MARKDOWN,
        "readme.markdown" to ICON_MARKDOWN,
        "readme.md" to ICON_MARKDOWN,
        "tsconfig.base.json" to ICON_JSON,
        "tsconfig.json" to ICON_JSON,
        )
    }
}
