-- AUTO-GENERATED by scripts/build-nvim.mjs — DO NOT EDIT BY HAND.
-- Public API for makinda-icons. Overlays Makinda's file-icon mappings onto
-- nvim-web-devicons (or mini.icons via the `mini` submodule). Safe to call
-- multiple times.

local M = {}

local data = require("makinda-icons.icons")

local function expand(map)
    local out = {}
    for key, name in pairs(map) do
        local def = data.icons[name]
        if def then out[key] = def end
    end
    return out
end

--- Apply Makinda's file-icon overlay to nvim-web-devicons.
--- Call this once after nvim-web-devicons is loaded (or pass it as
--- a dependency in your plugin manager).
---
--- @param opts table|nil
---   default_icon  boolean  -- override devicons' fallback icon (default: false)
function M.setup(opts)
    opts = opts or {}

    local ok, devicons = pcall(require, "nvim-web-devicons")
    if not ok then
        vim.notify(
            "[makinda-icons] nvim-web-devicons is required but not installed",
            vim.log.levels.WARN
        )
        return
    end

    devicons.set_icon(expand(data.by_extension))

    if devicons.set_icon_by_filename then
        devicons.set_icon_by_filename(expand(data.by_filename))
    end

    if opts.default_icon and data.icons.file and devicons.set_default_icon then
        local f = data.icons.file
        devicons.set_default_icon(f.icon, f.color, f.cterm_color)
    end
end

--- Convenience: get the Makinda definition for a known icon name.
--- @param name string
--- @return table|nil
function M.get(name)
    return data.icons[name]
end

M._data = data
return M
