-- AUTO-GENERATED by scripts/build-nvim.mjs — DO NOT EDIT BY HAND.
-- mini.icons-compatible overlay. Pass the returned table to
-- require("mini.icons").setup() (or merge into your existing config).
--
-- See: https://github.com/echasnovski/mini.icons

local data = require("makinda-icons.icons")

local function entry(name)
    local def = data.icons[name]
    if not def then return nil end
    -- mini.icons accepts { glyph = "…", hl = "MakindaXxx" } per key. We use
    -- a Makinda-prefixed highlight name so users can theme it themselves.
    return { glyph = def.icon, hl = "Makinda" .. def.name }
end

local function build(map)
    local out = {}
    for key, name in pairs(map) do
        local e = entry(name)
        if e then out[key] = e end
    end
    return out
end

local default_file = entry("file")

return {
    -- mini.icons looks up by extension first, then filename, then filetype.
    extension = build(data.by_extension),
    file = build(data.by_filename),
    default = default_file and { file = default_file } or nil,
}
