// Makinda Icons — Emacs emitter
//
// Reads scripts/manifest.mjs and scripts/nerd-font-glyphs.mjs and emits a
// single-file Emacs package that overlays Makinda's file-icon mappings onto
// nerd-icons.el (https://github.com/rainforest-cafe/nerd-icons.el).
//
//   • packages/emacs/makinda-icons.el   (single-file MELPA-ready package)
//
// Run: `npm run build:emacs`
//
// The package defines its own glyph helper `makinda-icons--glyph` and pushes
// entries onto `nerd-icons-extension-icon-alist` / `nerd-icons-regexp-icon-alist`
// when `(makinda-icons-setup)` is called. This works because nerd-icons looks
// up the icon function from the alist entry itself, so we sidestep the
// per-font name registry entirely.
//
// Same Nerd Font / monochrome caveats as the Neovim emitter.

import fs from "node:fs";
import path from "node:path";
import url from "node:url";
import { fileIcons } from "./manifest.mjs";
import { glyphTable } from "./nerd-font-glyphs.mjs";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const outDir = path.join(repoRoot, "packages", "emacs");
fs.mkdirSync(outDir, { recursive: true });

const pkgJson = JSON.parse(fs.readFileSync(path.join(repoRoot, "package.json"), "utf8"));

// ---------- Build mappings ----------

const usedNames = new Set();
const byExt = {};
const byFilename = {};

for (const icon of fileIcons) {
    if (!glyphTable[icon.name]) continue;
    usedNames.add(icon.name);
    for (const ext of icon.extensions ?? []) byExt[ext.toLowerCase()] = icon.name;
    for (const fn of icon.fileNames ?? []) byFilename[fn.toLowerCase()] = icon.name;
}
for (const generic of ["file", "folder", "folder-open"]) {
    if (glyphTable[generic]) usedNames.add(generic);
}

// ---------- Elisp emitters ----------

function elispStr(s) {
    return `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"`;
}

function elispEscapeRegex(s) {
    // Anchor exact filenames; escape regex metacharacters.
    return `\\\`${s.replace(/[.+*?^$()[\]{}|\\]/g, (c) => `\\${c}`)}\\'`;
}

function glyphChar(hex) {
    // Emacs string syntax: "\u{}" isn't supported; use ?\N{U+XXXX} via string,
    // or just embed the literal UTF-8. We use the literal codepoint via
    // `(string ?\NNNN)` style — but the simplest portable form is the actual
    // UTF-8 character in the source string.
    return String.fromCodePoint(parseInt(hex, 16));
}

const sortedNames = [...usedNames].sort();

const glyphEntries = sortedNames
    .map((name) => {
        const e = glyphTable[name];
        return `    (${elispStr(name)} . (${elispStr(glyphChar(e.glyph))} . ${elispStr(e.color)}))`;
    })
    .join("\n");

const extEntries = Object.keys(byExt)
    .sort()
    .map((ext) => `    (${elispStr(ext)} makinda-icons--render ${elispStr(byExt[ext])})`)
    .join("\n");

const filenameEntries = Object.keys(byFilename)
    .sort()
    .map(
        (fn) =>
            `    (${elispStr(elispEscapeRegex(fn))} makinda-icons--render ${elispStr(byFilename[fn])})`
    )
    .join("\n");

const elisp = `;;; makinda-icons.el --- Makinda file icons for Emacs -*- lexical-binding: t; -*-

;; Author: Makinda Jackson <hello@makinda.dev>
;; Maintainer: Makinda Jackson <hello@makinda.dev>
;; URL: https://github.com/makindajack/makinda-icons
;; Version: ${pkgJson.version}
;; Package-Requires: ((emacs "27.1") (nerd-icons "0.1.0"))
;; Keywords: faces, icons, files

;; This file is not part of GNU Emacs.

;; Released under the MIT License. See LICENSE.md in the upstream repo.

;;; Commentary:

;; AUTO-GENERATED by scripts/build-emacs.mjs from the Makinda Icons monorepo.
;; Do not edit by hand; re-run \`npm run build:emacs\` after changing
;; scripts/manifest.mjs or scripts/nerd-font-glyphs.mjs.
;;
;; Adds Makinda's file-icon overlay to nerd-icons.el.  Glyphs come from
;; Nerd Fonts (install one in your terminal/GUI font), colors come from the
;; Makinda palette.
;;
;; Usage:
;;
;;   (require 'makinda-icons)
;;   (makinda-icons-setup)
;;
;; With \`use-package\`:
;;
;;   (use-package makinda-icons
;;     :after nerd-icons
;;     :config (makinda-icons-setup))

;;; Code:

(require 'nerd-icons)

(defgroup makinda-icons nil
  "Makinda file icons for Emacs."
  :group 'nerd-icons
  :prefix "makinda-icons-")

(defconst makinda-icons--glyphs
  '(
${glyphEntries}
    )
  "Alist of (NAME . (GLYPH . HEX-COLOR)).
NAME matches the canonical icon id from scripts/manifest.mjs.")

(defun makinda-icons--render (name &rest args)
  "Return the Makinda glyph for NAME as a propertized string.
ARGS are passed through from the nerd-icons icon-alist call site; the
\`:face\` keyword is honored if provided, otherwise the Makinda palette
color from \`makinda-icons--glyphs\` is used as the foreground."
  (let* ((entry (cdr (assoc name makinda-icons--glyphs)))
         (glyph (or (car entry) "?"))
         (color (cdr entry))
         (face-arg (plist-get args :face))
         (face (or face-arg
                   (and color \`(:foreground ,color)))))
    (if face
        (propertize glyph 'face face)
      glyph)))

(defconst makinda-icons-extension-icon-alist
  '(
${extEntries}
    )
  "Extension → Makinda icon spec.  Same shape as
\`nerd-icons-extension-icon-alist\` so entries can be pushed there directly.")

(defconst makinda-icons-regexp-icon-alist
  '(
${filenameEntries}
    )
  "Filename regex → Makinda icon spec.  Same shape as
\`nerd-icons-regexp-icon-alist\`.  Anchored to the full filename.")

;;;###autoload
(defun makinda-icons-setup ()
  "Install Makinda's file-icon overlay onto nerd-icons.el.
Idempotent: re-running replaces any prior Makinda entries with the
current build.  Call this once after \`nerd-icons\` is loaded."
  (interactive)
  (dolist (e makinda-icons-extension-icon-alist)
    (setq nerd-icons-extension-icon-alist
          (cons e (assoc-delete-all (car e) nerd-icons-extension-icon-alist))))
  (dolist (e makinda-icons-regexp-icon-alist)
    (setq nerd-icons-regexp-icon-alist
          (cons e (assoc-delete-all (car e) nerd-icons-regexp-icon-alist))))
  (when (called-interactively-p 'interactive)
    (message "makinda-icons: %d ext, %d filename overlays installed"
             (length makinda-icons-extension-icon-alist)
             (length makinda-icons-regexp-icon-alist))))

;;;###autoload
(defun makinda-icons-icon-for-name (name &optional face)
  "Return the propertized Makinda glyph for icon NAME.
Optional FACE overrides the default palette face."
  (apply #'makinda-icons--render name (and face (list :face face))))

(provide 'makinda-icons)
;;; makinda-icons.el ends here
`;

const outFile = path.join(outDir, "makinda-icons.el");
fs.writeFileSync(outFile, elisp);

// ---------- Report ----------

const skipped = fileIcons.filter((i) => !glyphTable[i.name]).map((i) => i.name);

console.log("makinda-icons (emacs) build");
console.log(`  manifest entries:    ${fileIcons.length}`);
console.log(`  emitted icons:       ${sortedNames.length}`);
console.log(`  ext mappings:        ${Object.keys(byExt).length}`);
console.log(`  filename mappings:   ${Object.keys(byFilename).length}`);
console.log(`  skipped (no glyph):  ${skipped.length}`);
for (const s of skipped) console.log(`    • ${s}`);

console.log(`\nWrote: ${path.relative(repoRoot, outFile)}`);
console.log(`\nNext: load in Emacs and run M-x makinda-icons-setup`);
