// Makinda Icons — Neovim emitter
//
// Reads scripts/manifest.mjs (the single source of truth) and emits a Lua
// plugin that overlays Makinda's file-icon mappings onto
// nvim-web-devicons (https://github.com/nvim-tree/nvim-web-devicons).
//
//   • packages/nvim/lua/makinda-icons/icons.lua   (data: name → { icon, color, name })
//   • packages/nvim/lua/makinda-icons/init.lua    (setup() that calls devicons.set_icon)
//
// Run: `npm run build:nvim`
//
// Terminal Neovim is monochrome from a glyph perspective: each file type is
// represented by a Nerd Font codepoint, not the SVG itself. The codepoint
// table below is the canonical mapping. Colors come from Makinda's palette.
//
// References:
//   • nvim-web-devicons API: https://github.com/nvim-tree/nvim-web-devicons#api
//   • Nerd Fonts cheat sheet: https://www.nerdfonts.com/cheat-sheet

import fs from "node:fs";
import path from "node:path";
import url from "node:url";
import { fileIcons } from "./manifest.mjs";
import { glyphTable as iconTable } from "./nerd-font-glyphs.mjs";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const outRoot = path.join(repoRoot, "packages", "nvim", "lua", "makinda-icons");
fs.mkdirSync(outRoot, { recursive: true });

// Glyph + color table lives in scripts/nerd-font-glyphs.mjs (shared with
// the Emacs emitter so both Phase 3 and Phase 4 stay in lock-step).

const FALLBACK = iconTable.file;

// ---------- Build name → entry, ext → name, filename → name ----------

const usedNames = new Set();
const byExt = {};
const byFilename = {};

for (const icon of fileIcons) {
    if (!iconTable[icon.name]) continue; // only emit entries we have a glyph for
    usedNames.add(icon.name);
    for (const ext of icon.extensions ?? []) byExt[ext.toLowerCase()] = icon.name;
    for (const fn of icon.fileNames ?? []) byFilename[fn.toLowerCase()] = icon.name;
}

// Ensure the generic fallback names are always available even if the
// manifest doesn't bind any extension to them.
for (const generic of ["file", "folder", "folder-open"]) {
    if (iconTable[generic]) usedNames.add(generic);
}

// ---------- Lua emitters ----------

function pascal(name) {
    return name
        .split(/[-_]/)
        .map((p) => p[0]?.toUpperCase() + p.slice(1))
        .join("");
}

function luaStr(s) {
    return `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"`;
}

function luaTableLiteral(map) {
    const keys = Object.keys(map).sort();
    if (keys.length === 0) return "{}";
    const lines = keys.map((k) => {
        // Lua identifier-ish keys (letters, digits, underscores, no leading digit)
        // are emitted bare; everything else uses the [string] form.
        const bareOk = /^[A-Za-z_][A-Za-z0-9_]*$/.test(k);
        const key = bareOk ? k : `[${luaStr(k)}]`;
        return `    ${key} = ${luaStr(map[k])},`;
    });
    return `{\n${lines.join("\n")}\n}`;
}

const sortedNames = [...usedNames].sort();

const iconsLua = `-- AUTO-GENERATED by scripts/build-nvim.mjs — DO NOT EDIT BY HAND.
-- Source of truth: scripts/manifest.mjs

local M = {}

-- name → devicons entry. \`icon\` is a Nerd Font codepoint (utf-8 string).
M.icons = {
${sortedNames
        .map((name) => {
            const e = iconTable[name];
            return `    [${luaStr(name)}] = { icon = "\\u{${e.glyph}}", color = ${luaStr(e.color)}, cterm_color = ${luaStr(e.cterm_color)}, name = ${luaStr(pascal(name))} },`;
        })
        .join("\n")}
}

-- file extension (lowercase, no leading dot) → icon name
M.by_extension = ${luaTableLiteral(byExt)}

-- exact filename (lowercase) → icon name
M.by_filename = ${luaTableLiteral(byFilename)}

return M
`;

const initLua = `-- AUTO-GENERATED by scripts/build-nvim.mjs — DO NOT EDIT BY HAND.
-- Public API for makinda-icons. Overlays Makinda's file-icon mappings onto
-- nvim-web-devicons (or mini.icons via the \`mini\` submodule). Safe to call
-- multiple times.

local M = {}

local data = require("makinda-icons.icons")

local function expand(map)
    local out = {}
    for key, name in pairs(map) do
        local def = data.icons[name]
        if def then out[key] = def end
    end
    return out
end

--- Apply Makinda's file-icon overlay to nvim-web-devicons.
--- Call this once after nvim-web-devicons is loaded (or pass it as
--- a dependency in your plugin manager).
---
--- @param opts table|nil
---   default_icon  boolean  -- override devicons' fallback icon (default: false)
function M.setup(opts)
    opts = opts or {}

    local ok, devicons = pcall(require, "nvim-web-devicons")
    if not ok then
        vim.notify(
            "[makinda-icons] nvim-web-devicons is required but not installed",
            vim.log.levels.WARN
        )
        return
    end

    devicons.set_icon(expand(data.by_extension))

    if devicons.set_icon_by_filename then
        devicons.set_icon_by_filename(expand(data.by_filename))
    end

    if opts.default_icon and data.icons.file and devicons.set_default_icon then
        local f = data.icons.file
        devicons.set_default_icon(f.icon, f.color, f.cterm_color)
    end
end

--- Convenience: get the Makinda definition for a known icon name.
--- @param name string
--- @return table|nil
function M.get(name)
    return data.icons[name]
end

M._data = data
return M
`;

// ---------- mini.icons adapter ----------
//
// echasnovski/mini.icons exposes per-category override tables on
// MiniIcons.config (extension / file / filetype / etc.). We emit a
// ready-to-merge spec users can pass to \`require("mini.icons").setup()\`:
//
//     require("mini.icons").setup(require("makinda-icons.mini"))
//
// or merge by hand if they already have a config.

const miniLua = `-- AUTO-GENERATED by scripts/build-nvim.mjs — DO NOT EDIT BY HAND.
-- mini.icons-compatible overlay. Pass the returned table to
-- require("mini.icons").setup() (or merge into your existing config).
--
-- See: https://github.com/echasnovski/mini.icons

local data = require("makinda-icons.icons")

local function entry(name)
    local def = data.icons[name]
    if not def then return nil end
    -- mini.icons accepts { glyph = "…", hl = "MakindaXxx" } per key. We use
    -- a Makinda-prefixed highlight name so users can theme it themselves.
    return { glyph = def.icon, hl = "Makinda" .. def.name }
end

local function build(map)
    local out = {}
    for key, name in pairs(map) do
        local e = entry(name)
        if e then out[key] = e end
    end
    return out
end

local default_file = entry("file")

return {
    -- mini.icons looks up by extension first, then filename, then filetype.
    extension = build(data.by_extension),
    file = build(data.by_filename),
    default = default_file and { file = default_file } or nil,
}
`;

fs.writeFileSync(path.join(outRoot, "mini.lua"), miniLua);

fs.writeFileSync(path.join(outRoot, "icons.lua"), iconsLua);
fs.writeFileSync(path.join(outRoot, "init.lua"), initLua);

// ---------- Report ----------

const skipped = fileIcons
    .filter((i) => !iconTable[i.name])
    .map((i) => i.name);

console.log("makinda-icons (nvim) build");
console.log(`  manifest entries:    ${fileIcons.length}`);
console.log(`  emitted icons:       ${sortedNames.length}`);
console.log(`  ext mappings:        ${Object.keys(byExt).length}`);
console.log(`  filename mappings:   ${Object.keys(byFilename).length}`);
console.log(`  skipped (no glyph):  ${skipped.length}`);
for (const s of skipped) console.log(`    • ${s}`);

console.log(`\nWrote:`);
console.log(`  ${path.relative(repoRoot, path.join(outRoot, "icons.lua"))}`);
console.log(`  ${path.relative(repoRoot, path.join(outRoot, "init.lua"))}`);
console.log(`  ${path.relative(repoRoot, path.join(outRoot, "mini.lua"))}`);
console.log(`\nNext: install in Neovim and call require("makinda-icons").setup()`);
